version: "3.5"
services:
  mongo-single:
    image: mongo:latest
    container_name: mongo-single
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=aaa1234
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

