version: "3.5"
services:
  rabbitmq-management:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    environment:
      RABBITMQ_HIPE_COMPILE: "1"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672"
      - "15672:15672"