version: "3.5"

services:
  es:
    image: elasticsearch:7.14.0
    container_name: elasticsearch
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:7.14.0
    container_name: kibana
    ports:
      - "5601:5601"
